### ISSUE TITLE
unable to use session after destroy

### ISSUE THREAD

**Issue by rdp** [kemalcr/kemal-session#34]
Dunno if this is a bug per se, but surprised me.  After running an `env.session.destroy` if I access the session again in that request:

```
get "/logout" do |env|
  env.session.destroy
  env.session.string("flash", "successfully logged out")
  env.redirect "/login"
end
```

I get this:

```
Missing hash key: "9312da9064daec185cc58cb1bf3937f4" (KeyError)
0x82ec567: *Hash(String, String) at /opt/crystal/src/hash.cr 124:9
0x82ec42c: *Hash(String, String) at /opt/crystal/src/hash.cr 61:5
0x83289f8: *Session::MemoryEngine#string:String at /kemal_server/lib/kemal-session/src/kemal-session/engines/memory.cr 136:5
0x83295ef: *Session#string:String at .../kemal-session/src/kemal-session/engine.cr 48:3

```

(for followers, the work around is to not reuse flash anymore forthat request, it creates a new session on the next request seemingly.

**Comment by neovintage** [comment]
In the most literal sense, we've used `.destroy` to mean that we've removed the user session in its entirety. In this case, it seems we want to clear the session out instead of removing everything from the session store.

I'm inclined to make another method called `.clear` that empties out the contents of the session. Would that work? I'm trying to think of problems that might introduce.

**Comment by rdp** [comment]
Yeah that would be OK :)

**Comment by rdp** [comment]
I don't actually "need" this anymore since delete_XX have been added, so the current behavior might be OK.  A clear method would also be nice, so closing in favor of that.
